### PR TITLE
UI updated to advanced

### PR DESCRIPTION
**Pull request by Abhinandan-4321**
Have made the necessary changes as asked.

### CODE REVIEW

**Comment by Abhinandan-4321** [comment]
Hey, can you please review this PR.

**Comment by Merlinkk** [comment]
@CodiumAI-Agent /review

**Comment by Merlinkk** [comment]
@CodiumAI-Agent /review

**Comment by Abhinandan-4321** [comment]
is there a possibe change you would like me to do?

**Comment by Merlinkk** [comment]
> is there a possibe change you would like me to do?

The review given is not relevant to the functionality of the code. No need for changes.

**Comment by Abhinandan-4321** [comment]
Sure.

**Comment by Abhinandan-4321** [comment]
You can merge this PR now.

**Pull request merged**
